version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql_db
    volumes:
      - ./src/main/resources/application.properties:/app/src/main/resources/application.properties
    networks:
      - cpa-network
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: cpa_db
      MYSQL_USER: cpa
      MYSQL_PASSWORD: nE5kMc7JCGNqwDQM
      MYSQL_ROOT_PASSWORD: nE5kMc7JCGNqwDQN
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - cpa-network

networks:
  cpa-network:
    driver: bridge