version: "3.7"
services:

  mysql_db:
      image: "mysql:5.7"
      restart: always
      ports:
        - "3307:3306"
      environment:
        MYSQL_DATABASE: ${MYSQLDB_DATABASE}
        MYSQL_USER: ${MYSQLDB_USER}
        MYSQL_PASSWORD: ${MYSQLDB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQLDB_PASSWORD}
      volumes:
        - ./data:/var/lib/mysql
      networks:
        - cpa-network
  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
    environment:
        SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ./config:/config
    networks:
      - cpa-network

networks:
  cpa-network:
    driver: bridge