name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: joaopedrogama/cpa-api:latest
        Username: ${{ secrets.DOCKER_USER }}
        Password: ${{ secrets.DOCKER_TOKEN }}

#    - name: SSH to EC2 instance
#     uses: appleboy/ssh-action@master
#      with:
#        host: ${{ secrets.EC2_HOST }}
#        username: ${{ secrets.EC2_USERNAME }}
#        password: ${{ secrets.EC2_PASSWORD }}
